---
# Proxmox SSH Setup
- hosts: all
  tasks:
    #- name: Delete Config File
    #  ansible.builtin.file:
    #    path: ~/.ssh/config
    #    state: absent

    #- name: Create Config File
    #  ansible.builtin.file:
    #    path: ~/.ssh/config
    #    state: touch

    #- name: Copy Config File
    #  ansible.builtin.copy:
    #    dest: "~/.ssh/config"
    #    content: |
    #      Host {{ friendlyname }}
    #          User {{ username }}
    #          HostName {{ hostname }}


    #- name: Copy Keys
    #  ansible.builtin.command: ssh-copy-id {{ username }}@{{ hostname }}

    - name: Copy Keys
      ansible.posix.authorized_key:
        user: "{{var_ansible_user}}"
        state: present
        key: "{{var_ansible_ssh_pubkey}}"
